### ISSUE TITLE
Add archetype for assembly that adds new syntax highlighting

### ISSUE THREAD

**Issue by TylerJewell** [eclipse/che-archetypes#19]
One of the most common questions asked in our docs (and we have given different answers) is that people would like to update Orion editor with new syntax highlighting rules for a programming language that is not supported out of the box.  This is for customizers who want syntax highlighting but not ready (or cannot find) a language server.

Let's have an archetype that shows a custom assembly that adds a new language with syntax highlighting.  For example - this customer issue where they are just wanting syntax highlighting, but our first recommendation is to write a custom language server, which is overkill.

https://github.com/eclipse/che/issues/3638#issuecomment-279136845

**Comment by vparfonov** [comment]
will be covered #25
