### ISSUE TITLE
Adding custom stacks to an assembly

### ISSUE THREAD

**Issue by ghost** [eclipse/che-archetypes#20]
Investigate a way of adding custom stacks to a custom assembly

**Comment by mkuznyetsov** [comment]
I've sent Eugene an assembly with a new module `ide -> che-core-ide-stacks` where custom stacks.json and images can be placed, just like in Che.

In assembly-main, original stacks from Che will be replaced with custom ones.

**Comment by ghost** [comment]
We may have the same question for templates.

**Comment by mkuznyetsov** [comment]
Docs mention: https://github.com/eclipse/che-docs/pull/246
