### ISSUE TITLE
Create archetype from existed che sample sample-plugin-json

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse/che-archetypes#29]
It should be che + codenvy archetypes like  ```plugin-wizard-archetype```
Sample https://github.com/eclipse/che/tree/master/samples/sample-plugin-json

**Comment by mkuznyetsov** [comment]
Link for commit in cli-archetype branch
https://github.com/eclipse/che/commit/3a788d0320bba06bf05a29866a18ba0cd83ed0e0
