### ISSUE TITLE
Update Che CLI with `--che` and `--codenvy` options

### ISSUE THREAD

**Issue by TylerJewell** [eclipse/che-archetypes#42]
Make an improvement to the `archetype` command such that if you are building or running a generated archetype AND user provides `--che` or `--codenvy` command line parameter.

The default would be the `--che` parameter for build and run commands.

**Comment by mkuznyetsov** [comment]
Done in cli-archetype branch:
https://github.com/eclipse/che/commit/5a1a5dd369a5a51694b2051fb804f97ca3e3630b
https://github.com/eclipse/che/commit/8550165597f01d98085689f8742d3c2bdb5a172f
