### ISSUE TITLE
plugin-json-archetype generates project with compile errors (Constants.java)

### ISSUE THREAD

**Issue by vazexqi** [eclipse/che-archetypes#55]
Repro steps:

1. docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /Users/nchen/che/data:/data -v /Users/nchen/Development/che-sample:/archetype -v /Users/nchen/.m2/repository:/m2 eclipse/che-cli:5.15.0 archetype generate --group=com.vazexqi.sample
1. Examine the path to /che-sample/assembly/plugins/assembly/assembly-shared/src/main/java/com/vazexqi/sample/Constants.java

The issue is that you are not creating the necessary shared folder on the file system. See https://github.com/eclipse/che-archetypes/blob/master/plugin-json-archetype/src/main/resources/archetype-resources/plugins/__rootArtifactId__/__rootArtifactId__-shared/src/main/java/__packageInPathFormat__/Constants.java#L11

![screen shot 2017-07-26 at 9 33 49 am](https://user-images.githubusercontent.com/54414/28632560-d5f76226-71e5-11e7-9065-20c3d5cb9a8d.png)

**Comment by mkuznyetsov** [comment]
Fixed "shared" folder generation
